#ifndef FILE_PROCESSING_GLOBAL_H
#define FILE_PROCESSING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILE_PROCESSING_LIBRARY)
#  define FILE_PROCESSING_EXPORT Q_DECL_EXPORT
#else
#  define FILE_PROCESSING_EXPORT Q_DECL_IMPORT
#endif

#endif // FILE_PROCESSING_GLOBAL_H
